# Site settings
title: "BioVis 2019"
email: "website@biovis.net"
description: "Biological Data Visualization"
baseurl: "/2019"
#url: "http://biovis.github.io/biovis_2016"
url: "http://biovis.net"
conferenceshort: "BioVis 2019"
#FIX ME: the event number is most likely not correct
eventNum: "9th" 
IEEEconferencedate: "October 24, 2019"
ISMBconferencedate: "July 22, 2019"

# Old deadlines so I remember what they're called
# When everything breaks
#IEEE_deadline_submission: "TBD"
#IEEE_deadline_notification: "TBD"
#IEEE_deadline_camera: "TBD"
#IEEE_deadline_poster: "TBD"

#ISMB_hl_and_nresearch_submission: "TBD"
#ISMB_deadline_poster: "TBD"
#ISMB_hl_and_nresearch_notiication: "TBD"

ismb_paper_submission_deadline: "January 28, 2019"
ismb_paper_conditional_accept: "March 6, 2019"
ismb_paper_revised: "March 22, 2019"
ismb_paper_final_acceptance: "April 8, 2019"

biovis_paper_submission_deadline: "TBD"

ismb_abstract_submission_deadline: "April 11, 2019"

ismb_poster_submission_deadline: "May 15, 2019"
ismb_poster_accept: "May 23, 2019"
ismb_poster_oral_notification: TBD"

ismb_highlights_submission_deadline: "TBD"
ismb_highlights_accept: "TBD"

bmc_submission_deadline: ""
bmc_conditional_accept: ""
bmc_final_accpet: ""

# Build settings
markdown: kramdown

collections:
- posters_ISMB

google_analytics: "'UA-22015250-1'"
use_analytics: true
encoding: utf-8
